services:

  db:
    image: postgres:14.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: DB-Test
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust